version: '3.8'
# services / containers
services:
  # express app
  nest-ecourse-rehab-hati:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-ecourse-rehab-hati
    image: nest-ecourse-rehab-hati:1.0.0
    restart: always
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      # for prisma
      DATABASE_URL: mysql://root:my-secret-pw@db-ecourse-rehab-hati:3306/ecourse
    networks:
      - ecourse-rehab-hati
    depends_on:
      - db-ecourse-rehab-hati

  # mysql database
  db-ecourse-rehab-hati:
    container_name: db-ecourse-rehab-hati
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: ecourse
    volumes:
      - db-ecourse-rehab-hati:/var/lib/mysql
    networks:
      - ecourse-rehab-hati

# volumes
volumes:
  db-ecourse-rehab-hati:
    name: db-ecourse-rehab-hati

# networks
networks:
  ecourse-rehab-hati:
    name: ecourse-rehab-hati
    driver: bridge
